# Site settings
title: fj222hf's Blog
email: fj222hf@student.lnu.se
description: > # this means to ignore newlines until "baseurl:"
  This is fj222hf's blog site for the course 1dv022 on LNU.
  Here you'll find more information about myself and blog posts consering the 1dv022 course.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: ziktweeting
github_username:  fotzik

# Build settings
markdown: kramdown
